version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker pull gabrielcarl/fastapi-image:latest
      - run:
          name: Run Docker Container
          command: |
            docker run --rm gabrielcarl/fastapi-image:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build