version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t image-test ./CICD-Project/
      - run:
          name: Login no Docker Hub
          command: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Enviando Para DockerHub
          command: |
            
            docker tag image-test $DOCKERHUB_USERNAME/image-test:latest

            docker push $DOCKERHUB_USERNAME/image-test:latest

    
            