version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t image-test ./CICD-Project/
      - run:
          name: Run Docker Container
          command: |
            docker run image-test
      - run:
          name: remove Docker
          command: |
            docker stop image-test
            